// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFCUUOPV4Vwtt9e7TQX2GuD2_E7DVgMkM',
    appId: '1:909698455391:android:b88cfda0d4fdb12c1d08ea',
    messagingSenderId: '909698455391',
    projectId: 'neromoneyapp',
    storageBucket: 'neromoneyapp.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG-ox8zW8ui-nG4GFLkl74y-lTFuZ6PHc',
    appId: '1:909698455391:ios:49e6b3d29102bb6f1d08ea',
    messagingSenderId: '909698455391',
    projectId: 'neromoneyapp',
    storageBucket: 'neromoneyapp.firebasestorage.app',
    androidClientId: '909698455391-hm5jl5nv0uuihef59478t37b0qnvm72t.apps.googleusercontent.com',
    iosClientId: '909698455391-995vvenmqej79bfp3bsif9cq0oth54rl.apps.googleusercontent.com',
    iosBundleId: 'com.neromoney.neromoneyApp',
  );
}
